version: '3.8'
services:
  postgres:
    container_name: postgres-uea
    restart: always
    build: ./database
    ports:
      - '5432:5432'
  backend:
    container_name: backend-uea
    restart: always
    build: ./backend
    ports:
      - '8080:8080'
